#!/usr/bin/env bash
# USAGE: . clonerepo <repo URI>

ME=$(readlink "${BASH_SOURCE[0]}")
APP_DIR=$(dirname "$ME")

# shellcheck disable=SC2068
"$APP_DIR/gclone_repo" $@ > /tmp/gclone_output_023mf023mf
EXIT_CODE=$?

# Error checking
if [[ $EXIT_CODE != 0 ]]; then
    cat /tmp/gclone_output_023mf023mf
    exit $EXIT_CODE
fi

DIR=$(cat /tmp/gclone_output_023mf023mf)

if [ -z "$YK_FISH_EXISTS" ]; then
    # shellcheck disable=SC2164
    cd "$DIR"
else
    echo "$DIR"
fi
